name: Fetch and Save HTML with Retry

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to fetch'
        required: true
        default: 'https://www.avatrade.com.tw/trading-info/cfd-rollover-dates'
jobs:
  fetch-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make script executable
        run: chmod +x fetch_html.sh

      - name: Run Bash script to fetch HTML
        id: fetch
        env:
          URL: ${{ github.event.inputs.url }}
        run: |
          ./fetch_html.sh
          echo "::set-output name=html::$(cat cfd-rollover-dates.html | base64 -w 0)"

      - name: Upload HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cfd-rollover-dates
          path: cfd-rollover-dates.html