name: Fetch and Save HTML with Retry

on:
  push: # 每次代码提交触发
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to fetch'
        required: true
        default: 'https://www.avatrade.com.tw/trading-info/cfd-rollover-dates'
      file_name:
        description: 'File name to save'
        required: true
        default: 'cfd-rollover-dates.html'

jobs:
  fetch-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make script executable
        run: |
          chmod +x fetch_html.sh
          sudo chown -R $USER:$USER .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: cfd-rollover-dates.html

  # Deployment job
  deploy:
    needs: fetch-html
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4