name: Fetch and Save HTML with Retry

on:
  push: # 每次代码提交触发
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to fetch'
        required: true
        default: 'https://www.avatrade.com.tw/trading-info/cfd-rollover-dates'
      file_name:
        description: 'File name to save'
        required: true
        default: 'cfd-rollover-dates.html'

jobs:
  fetch-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # personal access token
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make script executable
        run: |
          chmod +x fetch_html.sh
          sudo chown -R $USER:$USER .

      # 配置 git
      - name: config git
        run: |
          git config --global user.email "q.curder@gmail.com"
          git config --global user.name "Curder"
      # 或者使用 git 命令
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "update by github actions"
      - name: push code to master
        run: git push origin master

