name: Fetch and Save HTML with Retry

on:
  push: # 每次代码提交触发
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to fetch'
        required: true
        default: 'https://www.avatrade.com.tw/trading-info/cfd-rollover-dates'
      file_name:
        description: 'File name to save'
        required: true
        default: 'cfd-rollover-dates.html'

jobs:
  fetch-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make script executable
        run: |
          chmod +x fetch_html.sh
          sudo chown -R $USER:$USER .

  deploy:
    runs-on: ubuntu-24.04
    needs: fetch-html
    steps:
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update HTML file cfd-rollover-dates.html $(date "+%Y-%m-%d %H:%M:%S")"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main